title: MrBig
theme: jekyll-theme-minimal
description: [Download](https://github.com/xymon-mrbig/MrBig/releases)</br>[Install](install.md)</br>[Configuration](configuration.md)</br>[Options](options.md)</br>[[Troubleshooting](troubleshooting.md)</br>[[External tests](externaltests.md)</br>[[Uninstall](uninstall.md)</br>[[Upgrade](upgrade.md)
